[project]
name = "hybrid-rag"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Amsalegebrehana", email = "se.amsale.gebrehana@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.141.1",
    "markdown-it-py>=4.2.0",
    "psycopg[binary]>=3.3.6",
    "sentence-transformers>=6.1.0",
]

[project.scripts]
hybrid-rag = "hybrid_rag:main"

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"
